#!/usr/bin/env bash
# ============================================================
# Virtual OTP System - Interactive Setup Script
# Run:  bash setup.sh
# Ye script tumse .env data maangega aur backend/.env bana dega
# Seed (admin + tables) app start hone pe automatically chalega
# ============================================================

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}"
echo "=============================================="
echo "   Virtual OTP System - Setup Wizard"
echo "=============================================="
echo -e "${NC}"

# ---------- Helpers ----------
ask() {
  local prompt="$1"
  local default="$2"
  local var
  if [ -n "$default" ]; then
    read -r -p "$prompt [$default]: " var
    echo "${var:-$default}"
  else
    read -r -p "$prompt: " var
    echo "$var"
  fi
}

ask_secret() {
  local prompt="$1"
  local var
  read -r -s -p "$prompt: " var
  echo
  echo "$var"
}

# ---------- Mode ----------
echo -e "${YELLOW}Deployment mode choose karo:${NC}"
echo "  1) Local (SQLite) - testing"
echo "  2) Local (PostgreSQL)"
echo "  3) Railway / Production (PostgreSQL) - sirf .env generate"
read -r -p "Choice [1]: " MODE
MODE=${MODE:-1}

# ---------- Common values ----------
echo ""
echo -e "${GREEN}=== Security & Admin ===${NC}"

SECRET_KEY=$(ask "SECRET_KEY (enter = auto generate)" "")
if [ -z "$SECRET_KEY" ]; then
  SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_hex(32))" 2>/dev/null || openssl rand -hex 32)
  echo -e "${GREEN}Generated SECRET_KEY${NC}"
fi

FIVESIM_API_KEY=$(ask "FIVESIM_API_KEY (required)" "")
while [ -z "$FIVESIM_API_KEY" ] || [ "$FIVESIM_API_KEY" = "your_5sim_api_key_here" ]; do
  echo -e "${RED}Real 5sim API key zaroori hai${NC}"
  FIVESIM_API_KEY=$(ask "FIVESIM_API_KEY" "")
done

ADMIN_USERNAME=$(ask "ADMIN_USERNAME" "admin")
ADMIN_EMAIL=$(ask "ADMIN_EMAIL" "admin@example.com")
ADMIN_PASSWORD=$(ask_secret "ADMIN_PASSWORD (hidden, strong password)")
while [ ${#ADMIN_PASSWORD} -lt 8 ]; do
  echo -e "${RED}Password min 8 characters${NC}"
  ADMIN_PASSWORD=$(ask_secret "ADMIN_PASSWORD")
done

DEFAULT_MARKUP=$(ask "DEFAULT_MARKUP_PERCENT" "50")

# ---------- Database ----------
echo ""
echo -e "${GREEN}=== Database ===${NC}"

if [ "$MODE" = "1" ]; then
  DATABASE_URL="sqlite:///./virtual_otp.db"
  CORS_ORIGINS="http://localhost:3000,http://127.0.0.1:3000"
  echo "Using SQLite: $DATABASE_URL"
elif [ "$MODE" = "2" ]; then
  PG_USER=$(ask "PostgreSQL username" "postgres")
  PG_PASS=$(ask_secret "PostgreSQL password")
  PG_HOST=$(ask "PostgreSQL host" "localhost")
  PG_PORT=$(ask "PostgreSQL port" "5432")
  PG_DB=$(ask "PostgreSQL database name" "virtual_otp")
  DATABASE_URL="postgresql://${PG_USER}:${PG_PASS}@${PG_HOST}:${PG_PORT}/${PG_DB}"
  CORS_ORIGINS="http://localhost:3000,http://127.0.0.1:3000"
else
  echo -e "${YELLOW}Railway mode: DATABASE_URL Railway dashboard se reference variable se aayega${NC}"
  echo "Yahan placeholder rakha ja raha hai. Railway pe set karna:"
  echo "  DATABASE_URL = \${{Postgres.DATABASE_URL}}"
  DATABASE_URL="postgresql://USER:PASS@HOST:5432/railway"
  FRONTEND_URL=$(ask "Frontend public URL (e.g. https://xxx.up.railway.app)" "https://your-frontend.up.railway.app")
  CORS_ORIGINS="${FRONTEND_URL},http://localhost:3000"
fi

# ---------- Write backend/.env ----------
mkdir -p backend
ENV_FILE="backend/.env"

cat > "$ENV_FILE" << EOF
# Auto-generated by setup.sh - $(date)
DATABASE_URL=${DATABASE_URL}

SECRET_KEY=${SECRET_KEY}
ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=1440

FIVESIM_API_KEY=${FIVESIM_API_KEY}

DEFAULT_MARKUP_PERCENT=${DEFAULT_MARKUP}

ADMIN_USERNAME=${ADMIN_USERNAME}
ADMIN_EMAIL=${ADMIN_EMAIL}
ADMIN_PASSWORD=${ADMIN_PASSWORD}

CORS_ORIGINS=${CORS_ORIGINS}
EOF

echo ""
echo -e "${GREEN}✓ backend/.env created successfully${NC}"

# ---------- Frontend .env.local ----------
if [ "$MODE" = "1" ] || [ "$MODE" = "2" ]; then
  mkdir -p frontend
  cat > frontend/.env.local << EOF
NEXT_PUBLIC_API_URL=http://localhost:8000
EOF
  echo -e "${GREEN}✓ frontend/.env.local created${NC}"
else
  BACKEND_URL=$(ask "Backend public URL (e.g. https://xxx.up.railway.app)" "https://your-backend.up.railway.app")
  mkdir -p frontend
  cat > frontend/.env.local << EOF
NEXT_PUBLIC_API_URL=${BACKEND_URL}
EOF
  echo -e "${GREEN}✓ frontend/.env.local created (for local reference)${NC}"
  echo -e "${YELLOW}Railway Frontend service me Variable set karo:${NC}"
  echo "  NEXT_PUBLIC_API_URL = ${BACKEND_URL}"
fi

# ---------- Summary ----------
echo ""
echo -e "${BLUE}=============================================="
echo "  SETUP COMPLETE"
echo "==============================================${NC}"
echo ""
echo "Admin credentials (save them):"
echo -e "  Username : ${GREEN}${ADMIN_USERNAME}${NC}"
echo -e "  Email    : ${GREEN}${ADMIN_EMAIL}${NC}"
echo -e "  Password : ${GREEN}(jo tumne diya)${NC}"
echo ""
echo "Next steps:"

if [ "$MODE" = "1" ] || [ "$MODE" = "2" ]; then
  echo "  1. Backend start:"
  echo "       cd backend && python -m venv venv && source venv/bin/activate"
  echo "       pip install -r requirements.txt"
  echo "       uvicorn app.main:app --reload --port 8000"
  echo ""
  echo "  2. Frontend start (new terminal):"
  echo "       cd frontend && npm install && npm run dev"
  echo ""
  echo "  Seed (admin + tables) pehli baar app start hone pe AUTOMATIC chalega."
else
  echo "  Railway pe jaao aur ye Variables set karo (Backend service):"
  echo "    DATABASE_URL      = \${{Postgres.DATABASE_URL}}"
  echo "    SECRET_KEY        = (generated above / from backend/.env)"
  echo "    FIVESIM_API_KEY   = ..."
  echo "    ADMIN_USERNAME    = ${ADMIN_USERNAME}"
  echo "    ADMIN_EMAIL       = ${ADMIN_EMAIL}"
  echo "    ADMIN_PASSWORD    = (jo tumne diya)"
  echo "    DEFAULT_MARKUP_PERCENT = ${DEFAULT_MARKUP}"
  echo "    CORS_ORIGINS      = ${CORS_ORIGINS}"
  echo ""
  echo "  Frontend service:"
  echo "    NEXT_PUBLIC_API_URL = (backend public URL)"
  echo ""
  echo "  Deploy ke baad seed AUTOMATIC chalega (tables + admin create)."
fi

echo ""
echo -e "${GREEN}Done!${NC}"
