export type CountryMeta = { label: string; iso: string };
export const COUNTRY_META: Record<string, CountryMeta> = {
  afghanistan: { label: "Afghanistan", iso: "af" },
  albania: { label: "Albania", iso: "al" },
  algeria: { label: "Algeria", iso: "dz" },
  angola: { label: "Angola", iso: "ao" },
  antiguaandbarbuda: { label: "Antigua and Barbuda", iso: "ag" },
  argentina: { label: "Argentina", iso: "ar" },
  armenia: { label: "Armenia", iso: "am" },
  aruba: { label: "Aruba", iso: "aw" },
  australia: { label: "Australia", iso: "au" },
  austria: { label: "Austria", iso: "at" },
  azerbaijan: { label: "Azerbaijan", iso: "az" },
  bahamas: { label: "Bahamas", iso: "bs" },
  bahrain: { label: "Bahrain", iso: "bh" },
  bangladesh: { label: "Bangladesh", iso: "bd" },
  barbados: { label: "Barbados", iso: "bb" },
  belgium: { label: "Belgium", iso: "be" },
  belize: { label: "Belize", iso: "bz" },
  benin: { label: "Benin", iso: "bj" },
  bhutane: { label: "Bhutan", iso: "bt" },
  bih: { label: "Bosnia and Herzegovina", iso: "ba" },
  bolivia: { label: "Bolivia", iso: "bo" },
  botswana: { label: "Botswana", iso: "bw" },
  brazil: { label: "Brazil", iso: "br" },
  bulgaria: { label: "Bulgaria", iso: "bg" },
  burkinafaso: { label: "Burkina Faso", iso: "bf" },
  burundi: { label: "Burundi", iso: "bi" },
  cambodia: { label: "Cambodia", iso: "kh" },
  cameroon: { label: "Cameroon", iso: "cm" },
  canada: { label: "Canada", iso: "ca" },
  capeverde: { label: "Cape Verde", iso: "cv" },
  chad: { label: "Chad", iso: "td" },
  chile: { label: "Chile", iso: "cl" },
  colombia: { label: "Colombia", iso: "co" },
  comoros: { label: "Comoros", iso: "km" },
  congo: { label: "Congo", iso: "cg" },
  costarica: { label: "Costa Rica", iso: "cr" },
  croatia: { label: "Croatia", iso: "hr" },
  cyprus: { label: "Cyprus", iso: "cy" },
  czech: { label: "Czech Republic", iso: "cz" },
  denmark: { label: "Denmark", iso: "dk" },
  djibouti: { label: "Djibouti", iso: "dj" },
  dominica: { label: "Dominica", iso: "dm" },
  dominicanrepublic: { label: "Dominican Republic", iso: "do" },
  ecuador: { label: "Ecuador", iso: "ec" },
  egypt: { label: "Egypt", iso: "eg" },
  england: { label: "United Kingdom", iso: "gb" },
  estonia: { label: "Estonia", iso: "ee" },
  ethiopia: { label: "Ethiopia", iso: "et" },
  finland: { label: "Finland", iso: "fi" },
  france: { label: "France", iso: "fr" },
  gabon: { label: "Gabon", iso: "ga" },
  gambia: { label: "Gambia", iso: "gm" },
  georgia: { label: "Georgia", iso: "ge" },
  germany: { label: "Germany", iso: "de" },
  ghana: { label: "Ghana", iso: "gh" },
  greece: { label: "Greece", iso: "gr" },
  guatemala: { label: "Guatemala", iso: "gt" },
  guinea: { label: "Guinea", iso: "gn" },
  haiti: { label: "Haiti", iso: "ht" },
  honduras: { label: "Honduras", iso: "hn" },
  hongkong: { label: "Hong Kong", iso: "hk" },
  hungary: { label: "Hungary", iso: "hu" },
  india: { label: "India", iso: "in" },
  indonesia: { label: "Indonesia", iso: "id" },
  ireland: { label: "Ireland", iso: "ie" },
  israel: { label: "Israel", iso: "il" },
  italy: { label: "Italy", iso: "it" },
  ivorycoast: { label: "Ivory Coast", iso: "ci" },
  jamaica: { label: "Jamaica", iso: "jm" },
  japan: { label: "Japan", iso: "jp" },
  jordan: { label: "Jordan", iso: "jo" },
  kazakhstan: { label: "Kazakhstan", iso: "kz" },
  kenya: { label: "Kenya", iso: "ke" },
  kuwait: { label: "Kuwait", iso: "kw" },
  kyrgyzstan: { label: "Kyrgyzstan", iso: "kg" },
  laos: { label: "Laos", iso: "la" },
  latvia: { label: "Latvia", iso: "lv" },
  lebanon: { label: "Lebanon", iso: "lb" },
  lesotho: { label: "Lesotho", iso: "ls" },
  liberia: { label: "Liberia", iso: "lr" },
  lithuania: { label: "Lithuania", iso: "lt" },
  luxembourg: { label: "Luxembourg", iso: "lu" },
  macau: { label: "Macau", iso: "mo" },
  madagascar: { label: "Madagascar", iso: "mg" },
  malawi: { label: "Malawi", iso: "mw" },
  malaysia: { label: "Malaysia", iso: "my" },
  maldives: { label: "Maldives", iso: "mv" },
  mali: { label: "Mali", iso: "ml" },
  malta: { label: "Malta", iso: "mt" },
  mauritania: { label: "Mauritania", iso: "mr" },
  mauritius: { label: "Mauritius", iso: "mu" },
  mexico: { label: "Mexico", iso: "mx" },
  moldova: { label: "Moldova", iso: "md" },
  mongolia: { label: "Mongolia", iso: "mn" },
  montenegro: { label: "Montenegro", iso: "me" },
  morocco: { label: "Morocco", iso: "ma" },
  mozambique: { label: "Mozambique", iso: "mz" },
  myanmar: { label: "Myanmar", iso: "mm" },
  namibia: { label: "Namibia", iso: "na" },
  nepal: { label: "Nepal", iso: "np" },
  netherlands: { label: "Netherlands", iso: "nl" },
  nicaragua: { label: "Nicaragua", iso: "ni" },
  niger: { label: "Niger", iso: "ne" },
  nigeria: { label: "Nigeria", iso: "ng" },
  northmacedonia: { label: "North Macedonia", iso: "mk" },
  norway: { label: "Norway", iso: "no" },
  oman: { label: "Oman", iso: "om" },
  pakistan: { label: "Pakistan", iso: "pk" },
  panama: { label: "Panama", iso: "pa" },
  paraguay: { label: "Paraguay", iso: "py" },
  peru: { label: "Peru", iso: "pe" },
  philippines: { label: "Philippines", iso: "ph" },
  poland: { label: "Poland", iso: "pl" },
  portugal: { label: "Portugal", iso: "pt" },
  puertoRico: { label: "Puerto Rico", iso: "pr" },
  qatar: { label: "Qatar", iso: "qa" },
  romania: { label: "Romania", iso: "ro" },
  russia: { label: "Russia", iso: "ru" },
  rwanda: { label: "Rwanda", iso: "rw" },
  saudiarabia: { label: "Saudi Arabia", iso: "sa" },
  senegal: { label: "Senegal", iso: "sn" },
  serbia: { label: "Serbia", iso: "rs" },
  seychelles: { label: "Seychelles", iso: "sc" },
  sierraleone: { label: "Sierra Leone", iso: "sl" },
  slovakia: { label: "Slovakia", iso: "sk" },
  slovenia: { label: "Slovenia", iso: "si" },
  solomonislands: { label: "Solomon Islands", iso: "sb" },
  southafrica: { label: "South Africa", iso: "za" },
  spain: { label: "Spain", iso: "es" },
  srilanka: { label: "Sri Lanka", iso: "lk" },
  suriname: { label: "Suriname", iso: "sr" },
  swaziland: { label: "Swaziland", iso: "sz" },
  sweden: { label: "Sweden", iso: "se" },
  taiwan: { label: "Taiwan", iso: "tw" },
  tajikistan: { label: "Tajikistan", iso: "tj" },
  tanzania: { label: "Tanzania", iso: "tz" },
  thailand: { label: "Thailand", iso: "th" },
  tit: { label: "Trinidad and Tobago", iso: "tt" },
  togo: { label: "Togo", iso: "tg" },
  tunisia: { label: "Tunisia", iso: "tn" },
  turkmenistan: { label: "Turkmenistan", iso: "tm" },
  uganda: { label: "Uganda", iso: "ug" },
  uruguay: { label: "Uruguay", iso: "uy" },
  usa: { label: "United States", iso: "us" },
  uzbekistan: { label: "Uzbekistan", iso: "uz" },
  venezuela: { label: "Venezuela", iso: "ve" },
  vietnam: { label: "Vietnam", iso: "vn" },
  zambia: { label: "Zambia", iso: "zm" },
};
export function countryLabel(slug: string) {
  if (!slug || slug === "any") return "Any (Cheapest)";
  return COUNTRY_META[slug]?.label || slug;
}
export function countryFlag(slug: string) {
  if (!slug || slug === "any") return "\uD83C\uDF10";
  const iso = COUNTRY_META[slug]?.iso;
  if (!iso) return "\uD83C\uDF10";
  return iso.toUpperCase().replace(/./g, (c) => String.fromCodePoint(127397 + c.charCodeAt(0)));
}

export function countryIso(slug: string): string | null {
  if (!slug || slug === "any") return null;
  return COUNTRY_META[slug]?.iso || null;
}
